---
title: "WRST BAEA BE-08 Field Deliverable Quality Control Report"
author: "SDMiller"
date: "2025-12-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(pointblank)

validate_rmd(summary=TRUE)

```

```{r,include=FALSE}

# Get the data from the BE-08 Survey Data deliverables
filename = 'BE-08 2024 WRST BAEA Survey Data Deliverable.csv'
dir = r'(C:\Work\VitalSigns\CAKN Bald Eagles\Data\2024\)' 
url = paste0(dir,filename) # Local file example
data = read.csv(url)
data$Date_O = as.Date(data$Date_O, format = "%m/%d/%Y")
data$Date_P = as.Date(data$Date_P, format = "%m/%d/%Y")
# glimpse(data)

```

# Informant

```{r,echo=FALSE,results='asis'}
create_informant(tbl = data,tbl_name = "BE-08",label = "BE-08: Data Table")
#print(informant)
outputfile = paste0(dir,"WRST BAEA BE-08 Field Deliverable Dataset Structure.html")
export_report(informant,filename = outputfile)

```

# VALID-I

```{r,echo=FALSE}
ScanTitle = paste0("WRST BAEA Quality Control Scan, ",format(Sys.time(), "%Y-%m-%d %H:%M:%S"))
agent <- 
  
  create_agent(
    #embed_report = TRUE,
    label=ScanTitle,
    tbl = data,
    tbl_name = "BE-08"
  ) %>%
  
  # QC-01: Standard columns exist
  col_exists(
    label="QC-01: Standard columns exist",
    brief="In order to flow the data from field deliverable BE-08 into the master database the standard columns must exist with correct column naming.",
    columns = c('Year','Date_O','Date_P','Territory ID','Nest_ID','Initiated','Nest_O','Status O Def','NumAds_O','AdBehav1_O','AdBehav2_O','Successful','StatusCode_P','Status P','Status P Def','NumYng','NumAds_P','River Segment Code','River Segment','Lat_DD','Lon','Lon_DD','Comments_O','Comments_P')
  ) %>%
  
  # QC-02: Required date fields are date
  col_is_date(
    label="QC-02: Required date fields are date",
    brief="Columns defined as data type Date must only contain valid dates.",
    columns = c('Date_O','Date_P')
  ) %>%
  
  # QC-03: Required bit fields are bit
  col_vals_between(
     label="QC-03: Required bit fields are bit",
     brief="Columns defined as data type Boolean (Bit) must only contain bit (0 or 1) values.",
     columns = c('Initiated','Successful'),
     inclusive = c(TRUE, TRUE),
     left = 0,
     right = 1,
     na_pass = TRUE
  ) %>%

  # QC-04: Initiated must be 1 or 0 unless NEST_O is NF or NC ('Not found' or 'Missed')
  col_vals_expr(
    expr = (Initiated %in% c(0, 1)) | (Nest_O %in% c("NF", "NC"))
  ) %>%

  interrogate()



# The below gets the agent results as a data frame
#agentDataFrame = agent %>% get_agent_report(display_table = FALSE)

# Show failing tests
# agentDataFrame %>% 
#                filter(n_pass == 0 | f_pass > 0) %>% 
#                select(i,type,columns,n_pass,f_pass) %>%
#                arrange(i,type,columns)


# Show the agent report
agent

# Output the report
outputfile = paste0(dir,"WRST BAEA BE-08 Field Deliverable Quality Control Report.html")
export_report(agent,filename = outputfile)

```
```{r,echo=FALSE,results='asis'}


cat("## Agent  \n\n")
print(agent)
cat("\n\n")

cat("## Results  \n\n")
print(kntitr::kable(agentDataFrame))
cat("\n\n")

  
```










